// Generated by CoffeeScript 1.6.3
(function() {
  window.enableEditor = function() {
    var editor;
    editor = window.ed = ace.edit("editor");
    editor.container.style.display = "block";
    editor.setTheme("ace/theme/monokai");
    editor.getSession().setMode("ace/mode/coffee");
    editor.commands.addCommand({
      name: 'execute',
      bindKey: {
        win: 'Ctrl-Enter'
      },
      exec: function(editor) {
        var source;
        source = editor.getValue();
        return CoffeeScript.run(source);
      }
    });
    return editor;
  };

}).call(this);
